Allow Records with Matching Name + Type
cloudposse/terraform-cloudflare-zone pull request #18
Opened 2022-10-13 22:17 UTC by milldr

## what
- Allowing for records to have the same Name and Type
- Added index to key for records map

## why
- We want to be able to create records that have the same name and type, so that we can create NS (different values)
- It is up to the user to ensure that duplicate records are not attempted to be created. Otherwise we would need to add name+type+_value_ as key for the record map

## references
- Closes #15 
- Closes #14

2022-10-13 22:19 UTC, milldr commented
/test all

2022-10-13 22:50 UTC, milldr commented
/test all

2022-10-13 23:37 UTC, nitrocode commented on main.tf
> +      index(local.flatten_records, record)
It's probably obvious but could you explain what the value of the index function would return as an example of a record input to this module?

2022-10-13 23:44 UTC, nitrocode requested changes
Thank you for putting in this PR.

@Nuru and I spoke of this change not too long ago and we decided that a key input would be the best path forward.

A few days ago we received this PR which does have the key input. It's worth reviewing that one instead of this one.

https://github.com/cloudposse/terraform-cloudflare-zone/pull/17/files

2022-10-14 00:07 UTC, milldr commented
Closing in favor of #17

2022-10-14 00:07 UTC, closed without merging